### ISSUE TITLE
Add javadocs checks on circle-ci

### ISSUE THREAD

**Issue by danielpassos** [aerogear/aerogear-android-sdk#100]
Javadocs problems make the build fail but actually, circle-ci is not checking any JavaDocs.

We should add the `./gradlew install` on circle-ci to avoid https://github.com/aerogear/aerogear-android-sdk/issues/97

**Comment by secondsun** [comment]
PR https://github.com/aerogear/aerogear-android-sdk/pull/109 should fix this issue.
