### ISSUE TITLE
Allow Developer to Choose Browser/Version Combinations for SSO

### ISSUE THREAD

**Issue by TommyJ1994** [aerogear/aerogear-android-sdk#105]
## Expected Behavior
I can choose a list of browsers or a single browser to whitelist/blacklist and specify minimum browser versions that can be used for authentication in my application to ensure that an insecure browser or version is not used for enterprise logins.

## Actual Behavior
Currently there is a hardcoded [blacklist](https://github.com/aerogear/aerogear-android-sdk/blob/3608e299b91131ce79f00891b21ae3f8f811b55c/auth/src/main/java/org/aerogear/mobile/auth/authenticator/AuthorizationServiceFactory.java#L85-L87) is for Chrome's Custom Tabs. 

## Specifications
  - Core SDK Version: 0.1.0.SNAPSHOT
  - Relevant Service Modules: auth

**Comment by aidenkeating** [comment]
@TommyJ1994 Is this still an issue? If so I'm happy to take it on

**Comment by TommyJ1994** [comment]
@aidenkeating Yes.
