### ISSUE TITLE
Replace callbacks with promise or reactive style APIs

### ISSUE THREAD

**Issue by secondsun** [aerogear/aerogear-android-sdk#122]
APIs in the SDK should not consume a callback as part of their parameters.  They should preferrable use a Reactive or promise style API design where possible, and use listener registration where not.

The reasoning behind this is that in Android it is easy to leak a reference to UI objects into longer lived code by passing a callback which is implemented as an anonymous inner class.

**Comment by wojta** [comment]
I think that it's good idea but it should be probably a part of a separate library wrapper for RxJava.

**Comment by secondsun** [comment]
Tracking JIRA https://issues.jboss.org/browse/AEROGEAR-2333

**Comment by secondsun** [comment]
JIRA is resolved, closing.
