### ISSUE TITLE
Rename Client to Resource for Roles

### ISSUE THREAD

**Issue by TommyJ1994** [aerogear/aerogear-android-sdk#138]
## Expected Behavior
Keycloak describes Clients as Resources in there documentation. I think we should reflect the same changes in order to ensure that the SDK's are using the same naming scheme. eg [JS Adapter](http://www.keycloak.org/docs/3.1/securing_apps/topics/oidc/javascript-adapter.html).

## Specifications

  - Core SDK Version: 0.0.1.SNAPSHOT
  - Relevant Service Modules: Auth

**Comment by rachael-oregan** [comment]
Resolved in #183
