### ISSUE TITLE
Allow retrieve Keycloak user attributes from the SDK

### ISSUE THREAD

**Issue by wei-lee** [aerogear/aerogear-android-sdk#139]
Keycloak allows setting arbitrary attributes on users as described [here](https://www.keycloak.org/docs/3.3/server_admin/topics/users/attributes.html).

We should update the SDK to retrieve these attributes from the user profile and allow developers to access them.

**Comment by TommyJ1994** [comment]
Implemented in https://github.com/aerogear/aerogear-android-sdk/pull/149
