### ISSUE TITLE
Self Defence Checks Doc Not Linked

### ISSUE THREAD

**Issue by TommyJ1994** [aerogear/aerogear-android-sdk#162]
The self defense checks [doc](https://github.com/aerogear/aerogear-android-sdk/blob/master/docs/getting-started/auth-self-defence-checks.adoc) is not visible to end users, We should add a link in a relevant document to link to this doc, otherwise its not visible to them unless they go through the file viewer in github.

**Comment by ciaranRoche** [comment]
Closing this issue as it was resolved https://github.com/aerogear/aerogear-android-sdk/pull/178
