### ISSUE TITLE
Example app crashes when metrics not found in configuration

### ISSUE THREAD

**Issue by aidenkeating** [aerogear/aerogear-android-sdk#189]
## Expected Behavior

If I add in my own `mobile-services.json` file to the example app it should still function. Even if I don't have every service provisioned.

This has only been confirmed when metrics is missing, other services may also cause this.

## Actual Behavior

If I add a `mobile-services.json` without `metrics` configured then the app will crash.

## Steps to Reproduce the Problem

  1. Remove metrics from `mobile-services.json`
  2. Run the app

**Comment by StephenCoady** [comment]
From looking at the code it looks like this line is breaking the application:

https://github.com/aerogear/aerogear-android-sdk/blob/master/core/src/main/java/org/aerogear/mobile/core/metrics/MetricsService.java#L53-L56

I'm not sure if it needs to be set as required all the time. If it doesn't then by the user providing the metrics in the json this line of code will never be triggered:

https://github.com/aerogear/aerogear-android-sdk/blob/master/core/src/main/java/org/aerogear/mobile/core/MobileCore.java#L163

and so the serviceCfg will always be set. If it does need to be set as required then this isn't a bug and the mobile-services.json needs to have metrics included. What do you think @aidenkeating?

**Comment by aidenkeating** [comment]
If a services `requiresConfiguration()` returns `true`, but its configuration isn't defined in `mobile-services.json` they'll need to handle the error. To me, this isn't a bug then, but something the end user should be aware they may need to handle in development.

IMO, the error should be handled in the example app. The example app should catch the `ConfigurationNotFoundException` and provide some feedback to the user that metrics/auth services are currently disabled because they're not defined in the configuration file.

That'll act as an example to the end user on how to handle this type of scenario (Which is probably only a development-time issue).

@secondsun @danielpassos Any opinion on this?

**Comment by danielpassos** [comment]
It's going be fixed when I finish [AGDROID-802](https://issues.jboss.org/browse/AGDROID-802)
