### ISSUE TITLE
Exception handling is a bit messy

### ISSUE THREAD

**Issue by ziccardi** [aerogear/aerogear-android-sdk#194]
Currently exception handling is a bit messy in the `JwsManager` class (see
[here](https://github.com/aerogear/aerogear-android-sdk/pull/192#discussion-diff-180148557R132))

Instead of assigning the exception to a variable and then perform checks if the variable is set or not, we could probably just throw and manage it in the catch block

**Comment by rachael-oregan** [comment]
@ziccardi I think this is no longer an issue.  Looks like the `JwksManager` class is handling errors correctly now.  

I'm going to close this issue.  Feel free to reopen if I misunderstood
