### ISSUE TITLE
Metrics integration test keeps failing

### ISSUE THREAD

**Issue by trepel** [aerogear/aerogear-android-sdk#265]
## Expected Behavior

Executing `./gradlew :core:testDebug --tests *.IntegrationTestSuite` produces no errors.

## Actual Behavior

Errors occur:
`java.lang.AssertionError: expected null, but was:<org.aerogear.mobile.core.exception.HttpException>`

The reason for this is that mock is used (this is also uncommon, you typically don't use mocks in integration tests, mocks are for unit testing) and its URL is hard coded in the test. See [MetricsServiceIntegrationTest.java](https://github.com/aerogear/aerogear-android-sdk/blob/master/core/src/test/java/org/aerogear/mobile/core/integration/MetricsServiceIntegrationTest.java#L33). It seems that this mock is not working as expected.

[CONTRIBUTING.md](https://github.com/aerogear/aerogear-android-sdk/blob/master/CONTRIBUTING.md) says that you need to configure the URL in [integration-test-mobile-services.json](https://github.com/aerogear/aerogear-android-sdk/blob/master/core/src/test/assets/integration-test-mobile-services.json#L11), but that file does not exist anymore. There are various files that I thought were meant for configuration of integration tests (e.g [mobile-services.json](https://github.com/aerogear/aerogear-android-sdk/blob/master/core/src/test/assets/mobile-services.json)) but since the URL for metrics endpoint is hard coded, changing the URL in the json has no effect.

I think the proper fix is to make the metrics endpoint configurable again and updating CONTRIBUTING.md to say how to configure it. I think it is OK to have a `http://localhost:3000/metrics` URL as default since that is the URL you can use if you run the service locally as described in its [README.md](https://github.com/aerogear/aerogear-app-metrics#run-entire-application-with-docker-compose)

## Steps to Reproduce the Problem

  1. `./gradlew clean install`
  1. `./gradlew :core:testDebug --tests *.IntegrationTestSuite`

**Comment by danielpassos** [comment]
Hey, @trepel if it fixes the problem, send a PR and I will take a look ;)

I'm going to hold on it from my side since you already have a solution.

**Comment by trepel** [comment]
@danielpassos Ok, I will do some polishing and create the PR then.

**Comment by trepel** [comment]
Fixed by https://github.com/aerogear/aerogear-android-sdk/pull/268. Closing the issue
