### ISSUE TITLE
Clean up documentation

### ISSUE THREAD

**Issue by pmacko1** [aerogear/aerogear-android-sdk#275]
in README.md
`Community Documentation: | https://aerogear.org`
- I don't believe that this is correct. (?)

`aerogear-android-sdk/docs/`
- troubleshooting.adoc -> Do we want to migrate this to docs.aerogear.org and delete it from here?
- README.adoc -> What do we want to tell here? I would propose telling that docs.aerogear.org has user facing documentation and the docs in `contrib/` host developer facing docs

`aerogear-android-sdk/docs/contrib`
- Do we want to migrate anything to docs.aerogear.org?

**Comment by danielpassos** [comment]
I think we can remove the docs folder. It's a nice question to shoot on ML

**Comment by pmacko1** [comment]
aerogear google group?

**Comment by danielpassos** [comment]
Yes!

**Comment by danielpassos** [comment]
@laurafitzgerald @finp thoughts?

**Comment by finp** [comment]
I have no opinion on deleting docs folder, it looks like troubleshooting has some unique content that could be transferred to mobile-docs repo, but should be edited first.
