### ISSUE TITLE
failed to add the AeroGear android sdk modules as dependencies to android projects by following the instructions

### ISSUE THREAD

**Issue by wei-lee** [aerogear/aerogear-android-sdk#46]
## Expected Behavior

I followed the instructions in the [getting-started guide](https://github.com/aerogear/aerogear-android-sdk/blob/master/docs/getting-started.adoc) to try adding the AG modules to [another android project](https://github.com/feedhenry/mobile-security-android-template).

I did installed the AG sdk modules locally first.

I would expect gradle will be able to find the dependencies and build the android app after following the instructions

## Actual Behavior

Gradle complains it can not find the module I specified. A few problems:

1. the group name is wrong. It looks like it should be `org.aerogear`
2. even after fixing the group id, gradle still can't find the module. I think it is because "org.jboss.aerogear:aerogear-android-sdk-bom" is using the wrong version number.

I managed to get it working by specify the full group id, artifact id and version number like this: https://github.com/feedhenry/mobile-security-android-template/blob/ce9a3fd29c52ea36009011bff78bde6b54146525/app/build.gradle#L53-L54

## Steps to Reproduce the Problem

  1. Follow the getting started instructions to setup the another android project.

**Comment by secondsun** [comment]
I'll take care of this @wei-lee

**Comment by secondsun** [comment]
https://github.com/aerogear/aerogear-android-sdk/pull/52

**Comment by danielpassos** [comment]
@wei-lee Can I close it?
