### ISSUE TITLE
Add/Expose method(s) to get parsed config from the mobile-services.json file

### ISSUE THREAD

**Issue by david-martin** [aerogear/aerogear-android-sdk#91]
## Expected Behavior

It doesn't seem to be possible to get specific values from the mobile-services.json file that the Core SDK has parsed. For example, I want to configure part of my App with the URL of where my Keycloak server is.
However, to do this currently, I'll have to manually re-read the mobile-services.json file myself, and parse out the keycloak url from the config structure.

It would be a lot handier if there was a way to get the raw config and/or the config for a specific service as a `JSONObject` or `ServiceConfiguration`

One way to do this is making the below method public
https://github.com/aerogear/aerogear-android-sdk/blob/3608e299b91131ce79f00891b21ae3f8f811b55c/core/src/main/java/org/aerogear/mobile/core/MobileCore.java#L169-L171
```java
private ServiceConfiguration getServiceConfiguration(final String type) {}
```

Another option is exposing a `getServiceConfig(String)` or `getKeycloakConfig()` method in `MobileCore`.
The former seems to be what the iOS SDK is doing
https://github.com/aerogear/aerogear-ios-sdk/blob/14fa3e6976faa0875ee591aa40d3fbecf936629c/modules/core/AgsCore.swift#L26

while the latter seems to be what the JS SDK is doing
https://github.com/aerogear/aerogear-js-sdk/blob/master/packages/core/src/Config.ts#L38-L44

We should probably standardize across SDKs and:

* decide if it should be possible to get the config
* decide if it should be done in a generic way
* decide if there should be service specific config methods e.g. `getKeycloakConfig()`

## Actual Behavior

No method is available to programatically get arbitrary values from the mobile-services.json file

**Comment by david-martin** [comment]
cc @TommyJ1994 @wei-lee @wtrocki @secondsun

**Comment by wtrocki** [comment]
JS SDK is just have couple additional helper methods but is 100 % compatible with the IOS. Method on the bottom can retrieve config in generic way. There is chance that JS implementation may not need specific SDK - we will use upstream js files together with configuration from openshift. It could be good to unify native solutions where we tend to wrap things even if upstream library may be available.
getKeycloak will be redundant for other platforms. I could remove this method from js but then entire class responsibility will be so trivial that we could question if we really need it for js.

**Comment by danielpassos** [comment]
That is weird, `getServiceConfiguration()` should be public. Make it public easy solve the problem I'm -1 to have any specific `getFoo()`

**Comment by david-martin** [comment]
I'm happy to close this based on #92 making the method public.

@danielpassos @wtrocki @pb82 Are there follow up issues/prs for the iOS & JS SDK to match this?

**Comment by pb82** [comment]
@david-martin The iOS SDK has a public `getConfiguration` method: https://github.com/aerogear/aerogear-ios-sdk/blob/master/modules/core/AgsCore.swift#L26

But the naming has to be adjusted and currently there is nothing like the `requiresConfiguration` option for modules on iOS.

**Comment by wtrocki** [comment]
@david-martin IOS and JS have public methods for this. No specific action required. 
We may review top level api for JS, Android and IOS before release and unify names and signatures.

**Comment by wei-lee** [comment]
@pb82 @wtrocki Take a quick look at the ios sample, if I am not mistaken, the returned `MobileService` instance is mutable. Is that right or it is a bug?

**Comment by wtrocki** [comment]
@wei-lee Here is PR with the change that was suggested: https://github.com/aerogear/aerogear-ios-sdk/pull/23

Feel free to can change SDK for our own needs in the future.
