### ISSUE TITLE
Gradlew install fails 

### ISSUE THREAD

**Issue by secondsun** [aerogear/aerogear-android-sdk#97]
## Expected Behavior
gradlew install should build the project and install it to maven local

## Actual Behavior
gradlew install fails to build the application because we have javadoc errors.

## Steps to Reproduce the Problem

  1. run gradlew install

## Specifications

  - Core SDK Version:
master

**Comment by secondsun** [comment]
Fixed by https://github.com/aerogear/aerogear-android-sdk/pull/99

**Comment by danielpassos** [comment]
Fixed by https://github.com/aerogear/aerogear-android-sdk/pull/99
